server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evenosis_auth
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000  # 24 hours
