server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/paymentdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:pwd}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.evenosis.paymentservice: DEBUG
    org.springframework.web: INFO
