spring:
  datasource:
    url: jdbc:postgresql://pg-role:5432/${ROLE_DB_NAME:roledb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
