spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://pg-user:5432/userdb
    username: postgres
    password: pwd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
