server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/userdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:pwd}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
